name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]  # main 브랜치에 push 이벤트가 발생할 때 워크플로우를 트리거합니다.

env:
  PROJECT_ID: 	even-arc-404608  # Google Cloud 프로젝트 ID
  SERVICE:  instance-1   # Cloud Run 서비스 이름
  REGION: us-west4             # Cloud Run 서비스 리전 (예: us-central1)

jobs:
  deploy:
    runs-on: ubuntu-latest  # 가장 최신의 Ubuntu 러너를 사용합니다.
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # GitHub 저장소의 코드를 체크아웃합니다.

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Base64로 인코딩된 서비스 계정 키
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |  # Cloud Run에 배포를 위한 gcloud CLI 명령어를 실행합니다.
          gcloud run deploy ${{ env.SERVICE }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated  # 외부에서의 비인증 접근을 허용합니다.
